src/Entity/Client.php
<?php

namespace App\Entity;

use App\Repository\ClientRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ClientRepository::class)
 */
class Client
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $prenom;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $code_postal;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $rue;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=32, nullable=true)
     */
    private $tel;

    /**
     * @ORM\OneToMany(targetEntity=Facture::class, mappedBy="client")
     */
    private $factures;

    /**
     * @ORM\OneToMany(targetEntity=Contrat::class, mappedBy="client")
     */
    private $contrats;

    /**
     * @ORM\OneToMany(targetEntity=Voiture::class, mappedBy="client")
     */
    private $voitures;

    public function __construct()
    {
        $this->factures = new ArrayCollection();
        $this->contrats = new ArrayCollection();
        $this->voitures = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(?string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getCodePostal(): ?int
    {
        return $this->code_postal;
    }

    public function setCodePostal(?int $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getRue(): ?string
    {
        return $this->rue;
    }

    public function setRue(?string $rue): self
    {
        $this->rue = $rue;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(?string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->tel;
    }

    public function setTel(?string $tel): self
    {
        $this->tel = $tel;

        return $this;
    }

    /**
     * @return Collection<int, Facture>
     */
    public function getFactures(): Collection
    {
        return $this->factures;
    }

    public function addFacture(Facture $facture): self
    {
        if (!$this->factures->contains($facture)) {
            $this->factures[] = $facture;
            $facture->setClient($this);
        }

        return $this;
    }

    public function removeFacture(Facture $facture): self
    {
        if ($this->factures->removeElement($facture)) {
            // set the owning side to null (unless already changed)
            if ($facture->getClient() === $this) {
                $facture->setClient(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Contrat>
     */
    public function getContrats(): Collection
    {
        return $this->contrats;
    }

    public function addContrat(Contrat $contrat): self
    {
        if (!$this->contrats->contains($contrat)) {
            $this->contrats[] = $contrat;
            $contrat->setClient($this);
            
        }

        return $this;
    }

    public function removeContrat(Contrat $contrat): self
    {
        if ($this->contrats->removeElement($contrat)) {
            // set the owning side to null (unless already changed)
            if ($contrat->getClient() === $this) {
                $contrat->setClient(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Voiture>
     */
    public function getVoitures(): Collection
    {
        return $this->voitures;
    }

    public function addVoiture(Voiture $voiture): self
    {
        if (!$this->voitures->contains($voiture)) {
            $this->voitures[] = $voiture;
            $voiture->setClient($this);
        }

        return $this;
    }

    public function removeVoiture(Voiture $voiture): self
    {
        if ($this->voitures->removeElement($voiture)) {
            // set the owning side to null (unless already changed)
            if ($voiture->getClient() === $this) {
                $voiture->setClient(null);
            }
        }

        return $this;
    }
}

src/Entity/Contrat.php
<?php

namespace App\Entity;

use App\Repository\ContratRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ContratRepository::class)
 */
class Contrat
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Client::class, inversedBy="contrats")
     * @ORM\JoinColumn(nullable=false)
     */
    private $client;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $type;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_depart;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_retour;

    /**
     * @ORM\OneToOne(targetEntity=Voiture::class, inversedBy="contrat", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=true)
     */
    private $voiture;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getDateDepart(): ?\DateTimeInterface
    {
        return $this->date_depart;
    }

    public function setDateDepart(?\DateTimeInterface $date_depart): self
    {
        $this->date_depart = $date_depart;

        return $this;
    }

    public function getDateRetour(): ?\DateTimeInterface
    {
        return $this->date_retour;
    }

   public function setDateRetour(?\DateTimeInterface $date_retour): self
    {
        $this->date_retour = $date_retour;

        return $this;
    } 

    public function getVoiture(): ?Voiture
    {
        return $this->voiture;
    }

    public function setVoiture(?Voiture $voiture): self
    {
        $this->voiture = $voiture;

        return $this;
    }
}

src/Entity/Facture.php
<?php

namespace App\Entity;

use App\Repository\FactureRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FactureRepository::class)
 */
class Facture
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Client::class, inversedBy="factures")
     * @ORM\JoinColumn(nullable=false)
     */
    private $client;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $compteur_km;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $montant_ht;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $montant_a_payer;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getlient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(?\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getCompteurKm(): ?int
    {
        return $this->compteur_km;
    }

    public function setCompteurKm(?int $compteur_km): self
    {
        $this->compteur_km = $compteur_km;

        return $this;
    }

    public function getMontantHt(): ?int
    {
        return $this->montant_ht;
    }

    public function setMontantHt(?int $montant_ht): self
    {
        $this->montant_ht = $montant_ht;

        return $this;
    }

    public function getMontantAPayer(): ?int
    {
        return $this->montant_a_payer;
    }

    public function setMontantAPayer(?int $montant_a_payer): self
    {
        $this->montant_a_payer = $montant_a_payer;

        return $this;
    }
}

src/Form/ClientType.php
<?php

namespace App\Form;

use App\Entity\Client;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ClientType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('prenom')
            ->add('rue')
            ->add('ville')
            ->add('code_postal')
            ->add('tel')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Client::class,
        ]);
    }
}

src/Controller/ClientController.php
<?php

namespace App\Controller;

use App\Entity\Client;
use App\Form\ClientType;
use App\Repository\ClientRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/client")
 */
class ClientController extends AbstractController
{
    /**
     * @Route("/", name="app_client_index", methods={"GET"})
     */
    public function index(ClientRepository $clientRepository): Response
    {
        return $this->render('client/index.html.twig', [
            'clients' => $clientRepository->findAll(),
            'chooseButton' => false, 
        ]);
    }

    /**
     * @Route("/new", name="app_client_new", methods={"GET", "POST"})
     */
    public function new(Request $request, ClientRepository $clientRepository): Response
    {
        $client = new Client();
        $form = $this->createForm(ClientType::class, $client);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $clientRepository->add($client, true);

            return $this->redirectToRoute('app_client_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('client/new.html.twig', [
            'client' => $client,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_client_show", methods={"GET"})
     */
    public function show(Client $client): Response
    {
        return $this->render('client/show.html.twig', [
            'client' => $client,
            'contrats' => $client->getContrats(),
            'factures' => $client->getFactures(),
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_client_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Client $client, ClientRepository $clientRepository): Response
    {
        $form = $this->createForm(ClientType::class, $client);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $clientRepository->add($client, true);

            return $this->redirectToRoute('app_client_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('client/edit.html.twig', [
            'client' => $client,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_client_delete", methods={"POST"})
     */
    public function delete(Request $request, Client $client, ClientRepository $clientRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$client->getId(), $request->request->get('_token'))) {
            $clientRepository->remove($client, true);
        }

        return $this->redirectToRoute('app_client_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/client/_delete_form.html.twig
<form style="display:inline;" method="post" action="{{ path('app_client_delete', {'id': client.id}) }}" onsubmit="return confirm('⚠️ Êtes-vous sûr de supprimer cela ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ client.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/client/_form.html.twig
{{ form_start(form) }}
    <div style="width: 500px;">
        {{ form_row(form.nom) }}
        {{ form_row(form.prenom, {label: 'Prénom'}) }}
        {{ form_row(form.rue, {label: 'Adresse'}) }}
        {{ form_row(form.ville, {'attr': {'class': 'form-inline'}}) }}
        {{ form_row(form.code_postal, {'attr': {'class': 'form-inline'}}) }}
        {{ form_row(form.tel, {label:'Téléphone'}) }}
    </div>
    <button type="submit" class="btn btn-success">{{ button_label|default('Enregistrer') }}</button>
    <br\>
{{ form_end(form) }}

templates/client/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier un client{% endblock %}

{% block body %}
    <h1>Modification du client n° {{ client.id }}</h1>

    {{ include('client/_form.html.twig', {'button_label': 'Mettre à jour'}) }}

    <a class="btn btn-primary" href="{{ path('app_client_index') }}">Retour à l'index</a>

    {{ include('client/_delete_form.html.twig') }}
{% endblock %}

templates/client/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Clients{% endblock %}

{% block body %}
    {% if chooseButton %}
        <h1>👨‍👩‍👧‍👦 Choisissez un client</h1>
    {% else %}
        <h1>👨‍👩‍👧‍👦 Index des clients</h1>
    {% endif %}

    <table class="table">
        <thead>
            <tr>
                <th>N°</th>
                <th>Nom</th>
                <th>Prénom</th>
                <th>Adresse</th>
                <th>Ville</th>
                <th>Code postal</th>
                <th>Téléphone</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for client in clients %}
            <tr>
                <td>{{ client.id }}</td>
                <td>{{ client.nom }}</td>
                <td>{{ client.prenom }}</td>
                <td>{{ client.rue }}</td>
                <td>{{ client.ville }}</td>
                <td>{{ client.codePostal }}</td>
                <td>{{ client.tel }}</td>
                <td>
                    {% if chooseButton %}
                        {% if choosePath == 'contrat' %}
                            <a class="btn btn-outline-primary btn-sm" href="{{ path('app_contrat_selectvoiture', {'id': client.id}) }}">Choisir</a>
                        {% elseif choosePath == 'facture'%}
                            <a class="btn btn-outline-primary btn-sm" href="{{ path('app_facture_new_setclient', {'id': client.id}) }}">Choisir</a>
                        {% endif %}
                    {% else %}
                        <a class="btn btn-outline-primary btn-sm" href="{{ path('app_client_show', {'id': client.id}) }}">Afficher</a>
                        <a class="btn btn-outline-primary btn-sm" href="{{ path('app_client_edit', {'id': client.id}) }}">Modifier</a>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">Aucun client trouvé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <a class="btn btn-primary" href="{{ path('app_client_new') }}">Ajouter un client</a>
{% endblock %}

templates/client/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau Client{% endblock %}

{% block body %}
    <h1>Ajouter un nouveau client</h1>

    {{ include('client/_form.html.twig') }}

    <a class="btn btn-primary" href="{{ path('app_client_index') }}">Retour à l'index</a>
{% endblock %}

templates/client/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Client{% endblock %}

{% block body %}
    <h1>Client</h1>

    <table class="table" style="width: 500px;">
        <tbody>
            <tr>
                <th>Numéro</th>
                <td>{{ client.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ client.nom }}</td>
            </tr>
            <tr>
                <th>Prénom</th>
                <td>{{ client.prenom }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ client.rue }}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ client.ville }}</td>
            </tr>
            <tr>
                <th>Code postal</th>
                <td>{{ client.codePostal }}</td>
            </tr>
            <tr>
                <th>Téléphone</th>
                <td>{{ client.tel }}</td>
            </tr>
        </tbody>
    </table>

    <a class="btn btn-primary" href="{{ path('app_client_edit', {'id': client.id}) }}">Modifier</a>
    {{ include('client/_delete_form.html.twig') }}

    
    <h2 style="padding-top: 1em">Contrats du client</h2>

    <table class="table">
        <thead>
            <tr>
                <th>N° de contrat</th>
                <th>Immatriculation</th>
                <th>Type</th>
                <th>Date départ</th>
                <th>Date retour</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for contrat in contrats %}
            <tr>
                <td>{{ contrat.id }}</td>
                <td>{{ contrat.voiture.immatriculation }}</td>
                <td>{{ contrat.type }}</td>
                <td>{{ contrat.dateDepart ? contrat.dateDepart|date('d/m/Y') : '' }}</td>
                <td>{{ contrat.dateRetour ? contrat.dateRetour|date('d/m/Y') : '' }}</td>
                <td>
                    <a class="btn btn-outline-primary btn-sm" href="{{ path('app_contrat_show', {'id': contrat.id}) }}">Afficher</a>
                    <a class="btn btn-outline-primary btn-sm" href="{{ path('app_contrat_edit', {'id': contrat.id}) }}">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">Aucun contrat trouvé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
      
    <a class="btn btn-primary" href="{{ path('app_contrat_selectvoiture', {'id': client.id}) }}">Créer un nouveau contrat</a>
    
    <h2 style="padding-top: 1em">Factures du client</h2>

    <table class="table">
        <thead>
            <tr>
                <th>N°</th>
                <th>Date</th>
                <th>Compteur km</th>
                <th>Montant HT</th>
                <th>Montant à payer</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for facture in factures %}
            <tr>
                <td>{{ facture.id }}</td>
                <td>{{ facture.date ? facture.date|date('d/m/Y') : '' }}</td>
                <td>{{ facture.compteurKm }}</td>
                <td>{{ facture.montantHt }}</td>
                <td>{{ facture.montantAPayer }}</td>
                <td>
                    <a class="btn btn-outline-primary btn-sm" href="{{ path('app_facture_show', {'id': facture.id}) }}">Afficher</a>
                    <a class="btn btn-outline-primary btn-sm" href="{{ path('app_facture_edit', {'id': facture.id}) }}">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">Aucune facture trouvée</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="btn btn-primary" href="{{ path('app_facture_new_setclient', {'id': client.id}) }}">Faire une nouvelle facture</a>
{% endblock %}